# Site settings
title: Startups and Technology
header-img: img/home-bg.jpg
email: h@londonstartuptech.com
description: "I write about startups and technology"
baseurl: ""
url: "http://writing.londonstartuptech.com"
twitter_username: h_carver
github_username:  hcarver

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
