# Site settings
title: Startups and Technology
header-img: img/home-bg.jpg
email: hywelc@gmail.com
description: "I write about startups and technology"
baseurl: ""
url: "http://writing.londonstartuptech.com"
twitter_username: h_carver
githuB_username:  hcarver

# Build settings
markdown: kramdown
excerpt_separator: "\n\n"
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins: ["jekyll-paginate"]
